base_images:
  base:
    name: ubi
    namespace: ocp
    tag: "8"
  cvp-operator-scorecard:
    name: cvp-operator-scorecard
    namespace: ci
    tag: v1
binary_build_commands: make build
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- dockerfile_path: Dockerfile
  from: bin
  inputs:
    base:
      as:
      - runtime
    bin:
      as:
      - builder
  to: redhat-operator-ecosystem-playground
promotion:
  namespace: ci
  tag: latest
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.7"
  namespace: ocp
tests:
- as: unit
  commands: make test-unit
  container:
    from: src
- as: perf
  commands: make test-perf
  container:
    from: src
- as: e2e
  steps:
    cluster_profile: aws
    test:
    - as: test
      cli: latest
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
- as: e2e-periodic
  cron: '@yearly'
  steps:
    cluster_profile: aws
    test:
    - as: test
      cli: latest
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: redhat-operator-ecosystem
  repo: playground
