releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      relative: 1
      stream: nightly
      version: "4.7"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cvp-common-aws
  cron: '@yearly'
  steps:
    cluster_profile: aws-cpaas
    workflow: optional-operators-cvp-common-aws
zz_generated_metadata:
  branch: cvp-ocp-4.7
  org: redhat-operator-ecosystem
  repo: playground
base_images:
  cvp-operator-scorecard:
    name: cvp-operator-scorecard
    namespace: ci
    tag: v1
